// Code generated by ent, DO NOT EDIT.

package box

import (
	"time"
)

const (
	// Label holds the string label denoting the box type in the database.
	Label = "box"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "created_at"
	// EdgeSections holds the string denoting the sections edge name in mutations.
	EdgeSections = "sections"
	// EdgePosition holds the string denoting the position edge name in mutations.
	EdgePosition = "position"
	// EdgeSystem holds the string denoting the system edge name in mutations.
	EdgeSystem = "system"
	// Table holds the table name of the box in the database.
	Table = "boxes"
	// SectionsTable is the table that holds the sections relation/edge.
	SectionsTable = "sections"
	// SectionsInverseTable is the table name for the Section entity.
	// It exists in this package in order to avoid circular dependency with the "section" package.
	SectionsInverseTable = "sections"
	// SectionsColumn is the table column denoting the sections relation/edge.
	SectionsColumn = "box_sections"
	// PositionTable is the table that holds the position relation/edge.
	PositionTable = "positions"
	// PositionInverseTable is the table name for the Position entity.
	// It exists in this package in order to avoid circular dependency with the "position" package.
	PositionInverseTable = "positions"
	// PositionColumn is the table column denoting the position relation/edge.
	PositionColumn = "box_position"
	// SystemTable is the table that holds the system relation/edge.
	SystemTable = "boxes"
	// SystemInverseTable is the table name for the System entity.
	// It exists in this package in order to avoid circular dependency with the "system" package.
	SystemInverseTable = "systems"
	// SystemColumn is the table column denoting the system relation/edge.
	SystemColumn = "system_boxes"
)

// Columns holds all SQL columns for box fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "boxes"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"system_boxes",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "createdAt" field.
	DefaultCreatedAt func() time.Time
)
