qrCodeImageFormat: "raspistill -o /tmp/qrcode.jpg -t 1"
qrCodeFilePath: "/tmp/qrcode.jpg"

standyTimeoutSeconds: 180
managerBaseUrl: "https://lagersystem.b49.cloudserver.click/api"

# global offset (use this to make sure zero is zero)
globalOffset: 5

# Position offset
positionOffset:
  x: 0
  y: 2
  z: 0

# Positon used for scanning the QR Code box
scanPosition:
  x: 0
  y: 683
  z: 60

# Input / Output Positions
ioPositions:
  "1":
    sensorPin: 17
    x: 0
    y: 683

  "2":
    sensorPin: 27
    x: 0
    y: 542

  "3":
    sensorPin: 22
    x: 0
    y: 386

# all the positions for storing boxes. key is the id of the position
positions: {
    # Magazine 1
    "1": { "x": 943.0, "y": 319 },
    "2": { "x": 867.5, "y": 319 },
    "3": { "x": 794.0, "y": 319 },
    "4": { "x": 720.0, "y": 320 },
    "5": { "x": 942.5, "y": 275.0 },
    "6": { "x": 868.5, "y": 276.0 },
    "7": { "x": 793.0, "y": 277.0 },
    "8": { "x": 719.0, "y": 278.0 },
    "9": { "x": 941.5, "y": 232.5 },
    "10": { "x": 867.0, "y": 233.5 },
    "11": { "x": 792.5, "y": 233.5 },
    "12": { "x": 718.5, "y": 233.5 },
    "13": { "x": 940.5, "y": 188.0 },
    "14": { "x": 865.0, "y": 188 },
    "15": { "x": 792.5, "y": 189.5 },
    "16": { "x": 717.0, "y": 190 },
    "17": { "x": 939.5, "y": 145 },
    "18": { "x": 864.5, "y": 145.0 },
    "19": { "x": 791.0, "y": 146 },
    "20": { "x": 717.5, "y": 146 },
    "21": { "x": 940.5, "y": 102.5 },
    "22": { "x": 865.5, "y": 102.5 },
    "23": { "x": 791.0, "y": 102.5 },
    "24": { "x": 716.5, "y": 102.5 },
    "25": { "x": 939.0, "y": 58.0 },
    "26": { "x": 864.0, "y": 59.0 },
    "27": { "x": 790.0, "y": 59.0 },
    "28": { "x": 715.0, "y": 59.5 },
    "29": { "x": 938.0, "y": 14.5 },
    "30": { "x": 864.0, "y": 14.5 },
    "31": { "x": 789.0, "y": 15.5 },
    "32": { "x": 714.0, "y": 17.0 },
    # Magazine 2
    "33": { "x": 949.0, "y": 731.5 },
    "34": { "x": 873.5, "y": 731.5 },
    "35": { "x": 800.0, "y": 732.5 },
    "36": { "x": 725.5, "y": 733.0 },
    "37": { "x": 947.0, "y": 687.5 },
    "38": { "x": 873.0, "y": 688.0 },
    "39": { "x": 798.5, "y": 689.5 },
    "40": { "x": 724.0, "y": 690.5 },
    "41": { "x": 947.0, "y": 644.5 },
    "42": { "x": 872.0, "y": 645.5 },
    "43": { "x": 798.0, "y": 646.0 },
    "44": { "x": 724.0, "y": 647.0 },
    "45": { "x": 946.0, "y": 600.5 },
    "46": { "x": 871.0, "y": 601.5 },
    "47": { "x": 797.0, "y": 602.0 },
    "48": { "x": 723.0, "y": 603.5 },
    "49": { "x": 944.5, "y": 557.0 },
    "50": { "x": 870.5, "y": 557.5 },
    "51": { "x": 797.0, "y": 558.5 },
    "52": { "x": 722.5, "y": 559.0 },
    "53": { "x": 944.0, "y": 513.5 },
    "54": { "x": 871.0, "y": 514.5 },
    "55": { "x": 796.5, "y": 515.0 },
    "56": { "x": 722.0, "y": 515.5 },
    "57": { "x": 943.0, "y": 470.5 },
    "58": { "x": 868.5, "y": 470.5 },
    "59": { "x": 795.0, "y": 471.5 },
    "60": { "x": 721.0, "y": 471.5 },
    "61": { "x": 943.0, "y": 426.5 },
    "62": { "x": 869.0, "y": 426.5 },
    "63": { "x": 794.0, "y": 427.0 },
    "64": { "x": 720.0, "y": 427.5 },
    # Magazine 3
    "65": { "x": 640, "y": 733.5 },
    "66": { "x": 564.6, "y": 735.5 },
    "67": { "x": 490.3, "y": 735.9 },
    "68": { "x": 416, "y": 735.9 },
    "69": { "x": 640.5, "y": 691 },
    "70": { "x": 564.6, "y": 692.2 },
    "71": { "x": 490.3, "y": 692.2 },
    "72": { "x": 416, "y": 692.2 },
    "73": { "x": 638.9, "y": 648 },
    "74": { "x": 564.6, "y": 648.5 },
    "75": { "x": 490.3, "y": 648.5 },
    "76": { "x": 416, "y": 648.5 },
    "77": { "x": 638.9, "y": 604 },
    "78": { "x": 564.6, "y": 604.8 },
    "79": { "x": 490.3, "y": 604.8 },
    "80": { "x": 416, "y": 604.8 },
    "81": { "x": 638.9, "y": 560 },
    "82": { "x": 564.6, "y": 561.1 },
    "83": { "x": 490.3, "y": 561.1 },
    "84": { "x": 416, "y": 561.1 },
    "85": { "x": 638.9, "y": 516 },
    "86": { "x": 564.6, "y": 517.4 },
    "87": { "x": 490.3, "y": 517.4 },
    "88": { "x": 416, "y": 517.4 },
    "89": { "x": 638.9, "y": 473 },
    "90": { "x": 564.6, "y": 473.7 },
    "91": { "x": 490.3, "y": 473.7 },
    "92": { "x": 416, "y": 473.7 },
    "93": { "x": 638.9, "y": 429 },
    "94": { "x": 564.6, "y": 430 },
    "95": { "x": 490.3, "y": 430 },
    "96": { "x": 416, "y": 430 },
    # Magazine 4
    "97": { "x": 334.5, "y": 735.9 },
    "98": { "x": 261, "y": 735.9 },
    "99": { "x": 186, "y": 735.9 },
    "100": { "x": 112.5, "y": 735.9 },
    "101": { "x": 334.5, "y": 692.2 },
    "102": { "x": 259.5, "y": 692.2 },
    "103": { "x": 186, "y": 692.2 },
    "104": { "x": 112, "y": 692.2 },
    "105": { "x": 333.5, "y": 648.5 },
    "106": { "x": 258.6, "y": 648 },
    "107": { "x": 184.3, "y": 648.5 },
    "108": { "x": 111, "y": 648.5 },
    "109": { "x": 333.5, "y": 604.8 },
    "110": { "x": 258.6, "y": 604.8 },
    "111": { "x": 184.3, "y": 604.8 },
    "112": { "x": 110, "y": 604.8 },
    "113": { "x": 332.9, "y": 561.1 },
    "114": { "x": 258.6, "y": 561.1 },
    "115": { "x": 184.3, "y": 561.1 },
    "116": { "x": 110, "y": 561.1 },
    "117": { "x": 332.9, "y": 517.4 },
    "118": { "x": 258.6, "y": 517.4 },
    "119": { "x": 184.3, "y": 517.4 },
    "120": { "x": 110.5, "y": 517.4 },
    "121": { "x": 332.9, "y": 473.7 },
    "122": { "x": 258.6, "y": 473.7 },
    "123": { "x": 184.3, "y": 473.7 },
    "124": { "x": 110, "y": 473.7 },
    "125": { "x": 332.9, "y": 430 },
    "126": { "x": 258.6, "y": 430 },
    "127": { "x": 184.3, "y": 430 },
    "128": { "x": 110, "y": 430 },
    # Magazine 5
    "129": { "x": 637.9, "y": 320.9 },
    "130": { "x": 563.6, "y": 320.9 },
    "131": { "x": 489.3, "y": 320.9 },
    "132": { "x": 414, "y": 320.9 },
    "133": { "x": 636, "y": 277.2 },
    "134": { "x": 561, "y": 277.2 },
    "135": { "x": 487, "y": 277.2 },
    "136": { "x": 413, "y": 277.2 },
    "137": { "x": 636, "y": 233.5 },
    "138": { "x": 561, "y": 233.5 },
    "139": { "x": 487, "y": 233.5 },
    "140": { "x": 413, "y": 233.5 },
    "141": { "x": 634, "y": 189.8 },
    "142": { "x": 560, "y": 189.8 },
    "143": { "x": 485, "y": 189.8 },
    "144": { "x": 411, "y": 189.8 },
    "145": { "x": 635, "y": 146.1 },
    "146": { "x": 560, "y": 146.1 },
    "147": { "x": 485, "y": 146.1 },
    "148": { "x": 411, "y": 146.1 },
    "149": { "x": 633, "y": 102.4 },
    "150": { "x": 559, "y": 102.4 },
    "151": { "x": 484, "y": 102.4 },
    "152": { "x": 410, "y": 102.4 },
    "153": { "x": 633, "y": 58.7 },
    "154": { "x": 559, "y": 58.7 },
    "155": { "x": 484, "y": 58.7 },
    "156": { "x": 410, "y": 58.7 },
    "157": { "x": 632, "y": 15 },
    "158": { "x": 558, "y": 15 },
    "159": { "x": 483, "y": 15 },
    "160": { "x": 409, "y": 15 },
    # Magazine 6
    "161": { "x": 330, "y": 320.9 },
    "162": { "x": 256, "y": 320.9 },
    "163": { "x": 181, "y": 320.9 },
    "164": { "x": 107, "y": 320.9 },
    "165": { "x": 330, "y": 277.2 },
    "166": { "x": 255, "y": 277.2 },
    "167": { "x": 181, "y": 277.2 },
    "168": { "x": 107, "y": 277.2 },
    "169": { "x": 330, "y": 233.5 },
    "170": { "x": 255, "y": 233.5 },
    "171": { "x": 181, "y": 233.5 },
    "172": { "x": 107, "y": 233.5 },
    "173": { "x": 330, "y": 189.8 },
    "174": { "x": 255, "y": 189.8 },
    "175": { "x": 179, "y": 189.8 },
    "176": { "x": 105, "y": 189.8 },
    "177": { "x": 328, "y": 146.1 },
    "178": { "x": 253, "y": 146.1 },
    "179": { "x": 179, "y": 146.1 },
    "180": { "x": 105, "y": 146.1 },
    "181": { "x": 326.9, "y": 102.4 },
    "182": { "x": 252.6, "y": 102.4 },
    "183": { "x": 178.3, "y": 102.4 },
    "184": { "x": 104, "y": 102.4 },
    "185": { "x": 326.9, "y": 58.7 },
    "186": { "x": 252.6, "y": 58.7 },
    "187": { "x": 178.3, "y": 58.7 },
    "188": { "x": 104, "y": 58.7 },
    "189": { "x": 326.9, "y": 15 },
    "190": { "x": 252.6, "y": 15 },
    "191": { "x": 178.3, "y": 15 },
    "192": { "x": 103, "y": 15 },
  }
