#!/usr/bin/env python

import sys
import movement

command = sys.argv[1].lower()

if command == "home":
  print("homing system")
  movement.home()

elif command == "gotoXY":
  movement.go_to_and_wait(float(sys.argv[2]), float(sys.argv[3]), None)
