// Code generated by ent, DO NOT EDIT.

package position

import (
	"time"
)

const (
	// Label holds the string label denoting the position type in the database.
	Label = "position"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "created_at"
	// FieldPositionId holds the string denoting the positionid field in the database.
	FieldPositionId = "position_id"
	// EdgeStoredBox holds the string denoting the storedbox edge name in mutations.
	EdgeStoredBox = "storedBox"
	// Table holds the table name of the position in the database.
	Table = "positions"
	// StoredBoxTable is the table that holds the storedBox relation/edge.
	StoredBoxTable = "positions"
	// StoredBoxInverseTable is the table name for the Box entity.
	// It exists in this package in order to avoid circular dependency with the "box" package.
	StoredBoxInverseTable = "boxes"
	// StoredBoxColumn is the table column denoting the storedBox relation/edge.
	StoredBoxColumn = "box_position"
)

// Columns holds all SQL columns for position fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldPositionId,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "positions"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"box_position",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "createdAt" field.
	DefaultCreatedAt func() time.Time
	// PositionIdValidator is a validator for the "positionId" field. It is called by the builders before save.
	PositionIdValidator func(int) error
)
