// Code generated by ent, DO NOT EDIT.

package position

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/niwla23/lagersystem/manager/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Position {
	return predicate.Position(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Position {
	return predicate.Position(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Position {
	return predicate.Position(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Position {
	return predicate.Position(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Position {
	return predicate.Position(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Position {
	return predicate.Position(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Position {
	return predicate.Position(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Position {
	return predicate.Position(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Position {
	return predicate.Position(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "createdAt" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Position {
	return predicate.Position(sql.FieldEQ(FieldCreatedAt, v))
}

// PositionId applies equality check predicate on the "positionId" field. It's identical to PositionIdEQ.
func PositionId(v int) predicate.Position {
	return predicate.Position(sql.FieldEQ(FieldPositionId, v))
}

// CreatedAtEQ applies the EQ predicate on the "createdAt" field.
func CreatedAtEQ(v time.Time) predicate.Position {
	return predicate.Position(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "createdAt" field.
func CreatedAtNEQ(v time.Time) predicate.Position {
	return predicate.Position(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "createdAt" field.
func CreatedAtIn(vs ...time.Time) predicate.Position {
	return predicate.Position(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "createdAt" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Position {
	return predicate.Position(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "createdAt" field.
func CreatedAtGT(v time.Time) predicate.Position {
	return predicate.Position(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "createdAt" field.
func CreatedAtGTE(v time.Time) predicate.Position {
	return predicate.Position(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "createdAt" field.
func CreatedAtLT(v time.Time) predicate.Position {
	return predicate.Position(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "createdAt" field.
func CreatedAtLTE(v time.Time) predicate.Position {
	return predicate.Position(sql.FieldLTE(FieldCreatedAt, v))
}

// PositionIdEQ applies the EQ predicate on the "positionId" field.
func PositionIdEQ(v int) predicate.Position {
	return predicate.Position(sql.FieldEQ(FieldPositionId, v))
}

// PositionIdNEQ applies the NEQ predicate on the "positionId" field.
func PositionIdNEQ(v int) predicate.Position {
	return predicate.Position(sql.FieldNEQ(FieldPositionId, v))
}

// PositionIdIn applies the In predicate on the "positionId" field.
func PositionIdIn(vs ...int) predicate.Position {
	return predicate.Position(sql.FieldIn(FieldPositionId, vs...))
}

// PositionIdNotIn applies the NotIn predicate on the "positionId" field.
func PositionIdNotIn(vs ...int) predicate.Position {
	return predicate.Position(sql.FieldNotIn(FieldPositionId, vs...))
}

// PositionIdGT applies the GT predicate on the "positionId" field.
func PositionIdGT(v int) predicate.Position {
	return predicate.Position(sql.FieldGT(FieldPositionId, v))
}

// PositionIdGTE applies the GTE predicate on the "positionId" field.
func PositionIdGTE(v int) predicate.Position {
	return predicate.Position(sql.FieldGTE(FieldPositionId, v))
}

// PositionIdLT applies the LT predicate on the "positionId" field.
func PositionIdLT(v int) predicate.Position {
	return predicate.Position(sql.FieldLT(FieldPositionId, v))
}

// PositionIdLTE applies the LTE predicate on the "positionId" field.
func PositionIdLTE(v int) predicate.Position {
	return predicate.Position(sql.FieldLTE(FieldPositionId, v))
}

// HasStoredBox applies the HasEdge predicate on the "storedBox" edge.
func HasStoredBox() predicate.Position {
	return predicate.Position(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, StoredBoxTable, StoredBoxColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStoredBoxWith applies the HasEdge predicate on the "storedBox" edge with a given conditions (other predicates).
func HasStoredBoxWith(preds ...predicate.Box) predicate.Position {
	return predicate.Position(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(StoredBoxInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, StoredBoxTable, StoredBoxColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Position) predicate.Position {
	return predicate.Position(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Position) predicate.Position {
	return predicate.Position(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Position) predicate.Position {
	return predicate.Position(func(s *sql.Selector) {
		p(s.Not())
	})
}
