// Code generated by ent, DO NOT EDIT.

package system

import (
	"time"
)

const (
	// Label holds the string label denoting the system type in the database.
	Label = "system"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "created_at"
	// FieldModifiedAt holds the string denoting the modifiedat field in the database.
	FieldModifiedAt = "modified_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// EdgeBoxes holds the string denoting the boxes edge name in mutations.
	EdgeBoxes = "boxes"
	// Table holds the table name of the system in the database.
	Table = "systems"
	// BoxesTable is the table that holds the boxes relation/edge.
	BoxesTable = "boxes"
	// BoxesInverseTable is the table name for the Box entity.
	// It exists in this package in order to avoid circular dependency with the "box" package.
	BoxesInverseTable = "boxes"
	// BoxesColumn is the table column denoting the boxes relation/edge.
	BoxesColumn = "system_boxes"
)

// Columns holds all SQL columns for system fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldModifiedAt,
	FieldName,
	FieldDescription,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "createdAt" field.
	DefaultCreatedAt func() time.Time
	// DefaultModifiedAt holds the default value on creation for the "modifiedAt" field.
	DefaultModifiedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
)
