// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Box is the predicate function for box builders.
type Box func(*sql.Selector)

// Part is the predicate function for part builders.
type Part func(*sql.Selector)

// Position is the predicate function for position builders.
type Position func(*sql.Selector)

// Property is the predicate function for property builders.
type Property func(*sql.Selector)

// Section is the predicate function for section builders.
type Section func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)
