// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/niwla23/lagersystem/manager/ent/box"
	"github.com/niwla23/lagersystem/manager/ent/position"
	"github.com/niwla23/lagersystem/manager/ent/predicate"
	"github.com/niwla23/lagersystem/manager/ent/section"
)

// BoxQuery is the builder for querying Box entities.
type BoxQuery struct {
	config
	ctx          *QueryContext
	order        []OrderFunc
	inters       []Interceptor
	predicates   []predicate.Box
	withSections *SectionQuery
	withPosition *PositionQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BoxQuery builder.
func (bq *BoxQuery) Where(ps ...predicate.Box) *BoxQuery {
	bq.predicates = append(bq.predicates, ps...)
	return bq
}

// Limit the number of records to be returned by this query.
func (bq *BoxQuery) Limit(limit int) *BoxQuery {
	bq.ctx.Limit = &limit
	return bq
}

// Offset to start from.
func (bq *BoxQuery) Offset(offset int) *BoxQuery {
	bq.ctx.Offset = &offset
	return bq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (bq *BoxQuery) Unique(unique bool) *BoxQuery {
	bq.ctx.Unique = &unique
	return bq
}

// Order specifies how the records should be ordered.
func (bq *BoxQuery) Order(o ...OrderFunc) *BoxQuery {
	bq.order = append(bq.order, o...)
	return bq
}

// QuerySections chains the current query on the "sections" edge.
func (bq *BoxQuery) QuerySections() *SectionQuery {
	query := (&SectionClient{config: bq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(box.Table, box.FieldID, selector),
			sqlgraph.To(section.Table, section.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, box.SectionsTable, box.SectionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(bq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPosition chains the current query on the "position" edge.
func (bq *BoxQuery) QueryPosition() *PositionQuery {
	query := (&PositionClient{config: bq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(box.Table, box.FieldID, selector),
			sqlgraph.To(position.Table, position.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, box.PositionTable, box.PositionColumn),
		)
		fromU = sqlgraph.SetNeighbors(bq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Box entity from the query.
// Returns a *NotFoundError when no Box was found.
func (bq *BoxQuery) First(ctx context.Context) (*Box, error) {
	nodes, err := bq.Limit(1).All(setContextOp(ctx, bq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{box.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (bq *BoxQuery) FirstX(ctx context.Context) *Box {
	node, err := bq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Box ID from the query.
// Returns a *NotFoundError when no Box ID was found.
func (bq *BoxQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = bq.Limit(1).IDs(setContextOp(ctx, bq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{box.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (bq *BoxQuery) FirstIDX(ctx context.Context) int {
	id, err := bq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Box entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Box entity is found.
// Returns a *NotFoundError when no Box entities are found.
func (bq *BoxQuery) Only(ctx context.Context) (*Box, error) {
	nodes, err := bq.Limit(2).All(setContextOp(ctx, bq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{box.Label}
	default:
		return nil, &NotSingularError{box.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (bq *BoxQuery) OnlyX(ctx context.Context) *Box {
	node, err := bq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Box ID in the query.
// Returns a *NotSingularError when more than one Box ID is found.
// Returns a *NotFoundError when no entities are found.
func (bq *BoxQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = bq.Limit(2).IDs(setContextOp(ctx, bq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{box.Label}
	default:
		err = &NotSingularError{box.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (bq *BoxQuery) OnlyIDX(ctx context.Context) int {
	id, err := bq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Boxes.
func (bq *BoxQuery) All(ctx context.Context) ([]*Box, error) {
	ctx = setContextOp(ctx, bq.ctx, "All")
	if err := bq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Box, *BoxQuery]()
	return withInterceptors[[]*Box](ctx, bq, qr, bq.inters)
}

// AllX is like All, but panics if an error occurs.
func (bq *BoxQuery) AllX(ctx context.Context) []*Box {
	nodes, err := bq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Box IDs.
func (bq *BoxQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	ctx = setContextOp(ctx, bq.ctx, "IDs")
	if err := bq.Select(box.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (bq *BoxQuery) IDsX(ctx context.Context) []int {
	ids, err := bq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (bq *BoxQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, bq.ctx, "Count")
	if err := bq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, bq, querierCount[*BoxQuery](), bq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (bq *BoxQuery) CountX(ctx context.Context) int {
	count, err := bq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (bq *BoxQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, bq.ctx, "Exist")
	switch _, err := bq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (bq *BoxQuery) ExistX(ctx context.Context) bool {
	exist, err := bq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BoxQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (bq *BoxQuery) Clone() *BoxQuery {
	if bq == nil {
		return nil
	}
	return &BoxQuery{
		config:       bq.config,
		ctx:          bq.ctx.Clone(),
		order:        append([]OrderFunc{}, bq.order...),
		inters:       append([]Interceptor{}, bq.inters...),
		predicates:   append([]predicate.Box{}, bq.predicates...),
		withSections: bq.withSections.Clone(),
		withPosition: bq.withPosition.Clone(),
		// clone intermediate query.
		sql:  bq.sql.Clone(),
		path: bq.path,
	}
}

// WithSections tells the query-builder to eager-load the nodes that are connected to
// the "sections" edge. The optional arguments are used to configure the query builder of the edge.
func (bq *BoxQuery) WithSections(opts ...func(*SectionQuery)) *BoxQuery {
	query := (&SectionClient{config: bq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bq.withSections = query
	return bq
}

// WithPosition tells the query-builder to eager-load the nodes that are connected to
// the "position" edge. The optional arguments are used to configure the query builder of the edge.
func (bq *BoxQuery) WithPosition(opts ...func(*PositionQuery)) *BoxQuery {
	query := (&PositionClient{config: bq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bq.withPosition = query
	return bq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"createdAt,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Box.Query().
//		GroupBy(box.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (bq *BoxQuery) GroupBy(field string, fields ...string) *BoxGroupBy {
	bq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BoxGroupBy{build: bq}
	grbuild.flds = &bq.ctx.Fields
	grbuild.label = box.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"createdAt,omitempty"`
//	}
//
//	client.Box.Query().
//		Select(box.FieldCreatedAt).
//		Scan(ctx, &v)
func (bq *BoxQuery) Select(fields ...string) *BoxSelect {
	bq.ctx.Fields = append(bq.ctx.Fields, fields...)
	sbuild := &BoxSelect{BoxQuery: bq}
	sbuild.label = box.Label
	sbuild.flds, sbuild.scan = &bq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BoxSelect configured with the given aggregations.
func (bq *BoxQuery) Aggregate(fns ...AggregateFunc) *BoxSelect {
	return bq.Select().Aggregate(fns...)
}

func (bq *BoxQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range bq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, bq); err != nil {
				return err
			}
		}
	}
	for _, f := range bq.ctx.Fields {
		if !box.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if bq.path != nil {
		prev, err := bq.path(ctx)
		if err != nil {
			return err
		}
		bq.sql = prev
	}
	return nil
}

func (bq *BoxQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Box, error) {
	var (
		nodes       = []*Box{}
		_spec       = bq.querySpec()
		loadedTypes = [2]bool{
			bq.withSections != nil,
			bq.withPosition != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Box).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Box{config: bq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, bq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := bq.withSections; query != nil {
		if err := bq.loadSections(ctx, query, nodes,
			func(n *Box) { n.Edges.Sections = []*Section{} },
			func(n *Box, e *Section) { n.Edges.Sections = append(n.Edges.Sections, e) }); err != nil {
			return nil, err
		}
	}
	if query := bq.withPosition; query != nil {
		if err := bq.loadPosition(ctx, query, nodes, nil,
			func(n *Box, e *Position) { n.Edges.Position = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (bq *BoxQuery) loadSections(ctx context.Context, query *SectionQuery, nodes []*Box, init func(*Box), assign func(*Box, *Section)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Box)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Section(func(s *sql.Selector) {
		s.Where(sql.InValues(box.SectionsColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.box_sections
		if fk == nil {
			return fmt.Errorf(`foreign-key "box_sections" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "box_sections" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (bq *BoxQuery) loadPosition(ctx context.Context, query *PositionQuery, nodes []*Box, init func(*Box), assign func(*Box, *Position)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Box)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	query.withFKs = true
	query.Where(predicate.Position(func(s *sql.Selector) {
		s.Where(sql.InValues(box.PositionColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.box_position
		if fk == nil {
			return fmt.Errorf(`foreign-key "box_position" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "box_position" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (bq *BoxQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := bq.querySpec()
	_spec.Node.Columns = bq.ctx.Fields
	if len(bq.ctx.Fields) > 0 {
		_spec.Unique = bq.ctx.Unique != nil && *bq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, bq.driver, _spec)
}

func (bq *BoxQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   box.Table,
			Columns: box.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: box.FieldID,
			},
		},
		From:   bq.sql,
		Unique: true,
	}
	if unique := bq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := bq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, box.FieldID)
		for i := range fields {
			if fields[i] != box.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := bq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := bq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := bq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := bq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (bq *BoxQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(bq.driver.Dialect())
	t1 := builder.Table(box.Table)
	columns := bq.ctx.Fields
	if len(columns) == 0 {
		columns = box.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if bq.sql != nil {
		selector = bq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if bq.ctx.Unique != nil && *bq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range bq.predicates {
		p(selector)
	}
	for _, p := range bq.order {
		p(selector)
	}
	if offset := bq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := bq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BoxGroupBy is the group-by builder for Box entities.
type BoxGroupBy struct {
	selector
	build *BoxQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (bgb *BoxGroupBy) Aggregate(fns ...AggregateFunc) *BoxGroupBy {
	bgb.fns = append(bgb.fns, fns...)
	return bgb
}

// Scan applies the selector query and scans the result into the given value.
func (bgb *BoxGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bgb.build.ctx, "GroupBy")
	if err := bgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BoxQuery, *BoxGroupBy](ctx, bgb.build, bgb, bgb.build.inters, v)
}

func (bgb *BoxGroupBy) sqlScan(ctx context.Context, root *BoxQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(bgb.fns))
	for _, fn := range bgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*bgb.flds)+len(bgb.fns))
		for _, f := range *bgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*bgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BoxSelect is the builder for selecting fields of Box entities.
type BoxSelect struct {
	*BoxQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (bs *BoxSelect) Aggregate(fns ...AggregateFunc) *BoxSelect {
	bs.fns = append(bs.fns, fns...)
	return bs
}

// Scan applies the selector query and scans the result into the given value.
func (bs *BoxSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bs.ctx, "Select")
	if err := bs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BoxQuery, *BoxSelect](ctx, bs.BoxQuery, bs, bs.inters, v)
}

func (bs *BoxSelect) sqlScan(ctx context.Context, root *BoxQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(bs.fns))
	for _, fn := range bs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*bs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
