// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/niwla23/lagersystem/manager/ent/part"
)

// Part is the model entity for the Part schema.
type Part struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "createdAt" field.
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PartQuery when eager-loading is set.
	Edges PartEdges `json:"edges"`
}

// PartEdges holds the relations/edges for other nodes in the graph.
type PartEdges struct {
	// Tags holds the value of the tags edge.
	Tags []*Tag `json:"tags,omitempty"`
	// Properties holds the value of the properties edge.
	Properties []*Property `json:"properties,omitempty"`
	// Sections holds the value of the sections edge.
	Sections []*Section `json:"sections,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// TagsOrErr returns the Tags value or an error if the edge
// was not loaded in eager-loading.
func (e PartEdges) TagsOrErr() ([]*Tag, error) {
	if e.loadedTypes[0] {
		return e.Tags, nil
	}
	return nil, &NotLoadedError{edge: "tags"}
}

// PropertiesOrErr returns the Properties value or an error if the edge
// was not loaded in eager-loading.
func (e PartEdges) PropertiesOrErr() ([]*Property, error) {
	if e.loadedTypes[1] {
		return e.Properties, nil
	}
	return nil, &NotLoadedError{edge: "properties"}
}

// SectionsOrErr returns the Sections value or an error if the edge
// was not loaded in eager-loading.
func (e PartEdges) SectionsOrErr() ([]*Section, error) {
	if e.loadedTypes[2] {
		return e.Sections, nil
	}
	return nil, &NotLoadedError{edge: "sections"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Part) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case part.FieldID:
			values[i] = new(sql.NullInt64)
		case part.FieldName:
			values[i] = new(sql.NullString)
		case part.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Part", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Part fields.
func (pa *Part) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case part.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pa.ID = int(value.Int64)
		case part.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field createdAt", values[i])
			} else if value.Valid {
				pa.CreatedAt = value.Time
			}
		case part.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				pa.Name = value.String
			}
		}
	}
	return nil
}

// QueryTags queries the "tags" edge of the Part entity.
func (pa *Part) QueryTags() *TagQuery {
	return NewPartClient(pa.config).QueryTags(pa)
}

// QueryProperties queries the "properties" edge of the Part entity.
func (pa *Part) QueryProperties() *PropertyQuery {
	return NewPartClient(pa.config).QueryProperties(pa)
}

// QuerySections queries the "sections" edge of the Part entity.
func (pa *Part) QuerySections() *SectionQuery {
	return NewPartClient(pa.config).QuerySections(pa)
}

// Update returns a builder for updating this Part.
// Note that you need to call Part.Unwrap() before calling this method if this Part
// was returned from a transaction, and the transaction was committed or rolled back.
func (pa *Part) Update() *PartUpdateOne {
	return NewPartClient(pa.config).UpdateOne(pa)
}

// Unwrap unwraps the Part entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pa *Part) Unwrap() *Part {
	_tx, ok := pa.config.driver.(*txDriver)
	if !ok {
		panic("ent: Part is not a transactional entity")
	}
	pa.config.driver = _tx.drv
	return pa
}

// String implements the fmt.Stringer.
func (pa *Part) String() string {
	var builder strings.Builder
	builder.WriteString("Part(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pa.ID))
	builder.WriteString("createdAt=")
	builder.WriteString(pa.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(pa.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Parts is a parsable slice of Part.
type Parts []*Part

func (pa Parts) config(cfg config) {
	for _i := range pa {
		pa[_i].config = cfg
	}
}
