// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/niwla23/lagersystem/manager/ent/box"
	"github.com/niwla23/lagersystem/manager/ent/part"
	"github.com/niwla23/lagersystem/manager/ent/section"
)

// SectionCreate is the builder for creating a Section entity.
type SectionCreate struct {
	config
	mutation *SectionMutation
	hooks    []Hook
}

// SetCreatedAt sets the "createdAt" field.
func (sc *SectionCreate) SetCreatedAt(t time.Time) *SectionCreate {
	sc.mutation.SetCreatedAt(t)
	return sc
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (sc *SectionCreate) SetNillableCreatedAt(t *time.Time) *SectionCreate {
	if t != nil {
		sc.SetCreatedAt(*t)
	}
	return sc
}

// SetUpdatedAt sets the "updatedAt" field.
func (sc *SectionCreate) SetUpdatedAt(t time.Time) *SectionCreate {
	sc.mutation.SetUpdatedAt(t)
	return sc
}

// SetNillableUpdatedAt sets the "updatedAt" field if the given value is not nil.
func (sc *SectionCreate) SetNillableUpdatedAt(t *time.Time) *SectionCreate {
	if t != nil {
		sc.SetUpdatedAt(*t)
	}
	return sc
}

// SetBoxID sets the "box" edge to the Box entity by ID.
func (sc *SectionCreate) SetBoxID(id int) *SectionCreate {
	sc.mutation.SetBoxID(id)
	return sc
}

// SetNillableBoxID sets the "box" edge to the Box entity by ID if the given value is not nil.
func (sc *SectionCreate) SetNillableBoxID(id *int) *SectionCreate {
	if id != nil {
		sc = sc.SetBoxID(*id)
	}
	return sc
}

// SetBox sets the "box" edge to the Box entity.
func (sc *SectionCreate) SetBox(b *Box) *SectionCreate {
	return sc.SetBoxID(b.ID)
}

// AddPartIDs adds the "parts" edge to the Part entity by IDs.
func (sc *SectionCreate) AddPartIDs(ids ...int) *SectionCreate {
	sc.mutation.AddPartIDs(ids...)
	return sc
}

// AddParts adds the "parts" edges to the Part entity.
func (sc *SectionCreate) AddParts(p ...*Part) *SectionCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return sc.AddPartIDs(ids...)
}

// Mutation returns the SectionMutation object of the builder.
func (sc *SectionCreate) Mutation() *SectionMutation {
	return sc.mutation
}

// Save creates the Section in the database.
func (sc *SectionCreate) Save(ctx context.Context) (*Section, error) {
	if err := sc.defaults(); err != nil {
		return nil, err
	}
	return withHooks[*Section, SectionMutation](ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SectionCreate) SaveX(ctx context.Context) *Section {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *SectionCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *SectionCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sc *SectionCreate) defaults() error {
	if _, ok := sc.mutation.CreatedAt(); !ok {
		if section.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized section.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := section.DefaultCreatedAt()
		sc.mutation.SetCreatedAt(v)
	}
	if _, ok := sc.mutation.UpdatedAt(); !ok {
		if section.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized section.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := section.DefaultUpdatedAt()
		sc.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (sc *SectionCreate) check() error {
	if _, ok := sc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "createdAt", err: errors.New(`ent: missing required field "Section.createdAt"`)}
	}
	if _, ok := sc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updatedAt", err: errors.New(`ent: missing required field "Section.updatedAt"`)}
	}
	return nil
}

func (sc *SectionCreate) sqlSave(ctx context.Context) (*Section, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *SectionCreate) createSpec() (*Section, *sqlgraph.CreateSpec) {
	var (
		_node = &Section{config: sc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: section.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: section.FieldID,
			},
		}
	)
	if value, ok := sc.mutation.CreatedAt(); ok {
		_spec.SetField(section.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := sc.mutation.UpdatedAt(); ok {
		_spec.SetField(section.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := sc.mutation.BoxIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   section.BoxTable,
			Columns: []string{section.BoxColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: box.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.box_sections = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.PartsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   section.PartsTable,
			Columns: []string{section.PartsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: part.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SectionCreateBulk is the builder for creating many Section entities in bulk.
type SectionCreateBulk struct {
	config
	builders []*SectionCreate
}

// Save creates the Section entities in the database.
func (scb *SectionCreateBulk) Save(ctx context.Context) ([]*Section, error) {
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Section, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SectionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *SectionCreateBulk) SaveX(ctx context.Context) []*Section {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *SectionCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *SectionCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
